#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
Bundler.require(:default)
require "#{__dir__}/lib/manuscript"

if ARGV.count == 1 && TARGETS.include?(ARGV[0])
  TARGET.new(:default, ARGV[0]).compile
  puts "Done!"
else
  puts "Nothing was done; invalid target. Valid targets are html, tex, or epub."
end